### ISSUE TITLE
[BUG] - Bun support

### ISSUE THREAD

**Issue by KookaS** [nextui-org/nextui#1076]
### Describe the bug

I am running the project locally using devcontainer: `mcr.microsoft.com/devcontainers/typescript-node:0-18`
It says it is a React bug but I do not think so. I tried installing MaterialUI and it works just fine, so it should be related to NextUI.

### Steps to Reproduce the Bug or Issue

1. install bun `curl -fsSL https://bun.sh/install | bash`
2. in _app.tsx
```js
<NextUIProvider>
    <Component {...pageProps} />
</NextUIProvider>
```
3. in package.json
```json
"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }
```
4. run `bun dev`

### Expected behavior

[0.04ms] "node_modules.bun" - 73 modules, 6 packages
[1.00ms] bun!! v0.5.7 (5929daee)

  Link: http://localhost:3000

404 GET /_next/webpack-hmr as application/octet-stream
[0.06ms] "node_modules.server.bun" - 48 modules, 6 packages
[34.18ms] Next.js ready! (powered by bun)
Error loading page: /workspaces/my-project/pages/index.tsx
323 |       error('disabledDepth fell below zero. ' + 'This is a bug in React. Please file an issue.');
324 |     }
325 |   }
326 | }
327 | 
328 | var ReactCurrentDispatcher = ReactSharedInternals.ReactCurrentDispatcher;
                                 ^
TypeError: undefined is not an object (evaluating 'ReactSharedInternals.ReactCurrentDispatcher')
      at /workspaces/my-project/node_modules/react/cjs/react-jsx-runtime.development.js:328:29
      at /workspaces/my-project/node_modules/react/cjs/react-jsx-runtime.development.js:1312:15
      at http://localhost:3000/blob:node_modules.server.bun:1:16452
      at /workspaces/my-project/node_modules/react/jsx-runtime.js:6:9
      at http://localhost:3000/blob:node_modules.server.bun:1:16452
      at /workspaces/my-project/node_modules/@mui/base/utils/ClassNameConfigurator.js:2:0
      at /workspaces/my-project/node_modules/@mui/base/utils/index.js:3:0
      at /workspaces/my-project/node_modules/@mui/material/AppBar/index.js:1:0
323 |       error('disabledDepth fell below zero. ' + 'This is a bug in React. Please file an issue.');
324 |     }
325 |   }
326 | }
327 | 
328 | var ReactCurrentDispatcher = ReactSharedInternals.ReactCurrentDispatcher;

### Operating System Version

Debian GNU/Linux 11 (bullseye)

### Browser

Chrome

**Comment by KookaS** [comment]
It is actually a problem related to nextjs, not nextui specifically.
