### ISSUE TITLE
[SEO] Using <meta/> not possible without triggering <SSRProvider> warnings

### ISSUE THREAD

**Issue by OrganisationMan** [nextui-org/nextui#1080]
### Describe the bug

Metatags won't load correctly if you're using conditional rendering inside `_app.js`. 

**Example 1:**
```js
 const { isBrowser } = useSSR();
  return (
    isBrowser && (
      <>
        <Head>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>EXAMPLE ON TITLE</title>
          <meta name="title" content="TITLE" />
          <meta name="description" content="DESCRIPTION" />
        </Head>
        <NextUIProvider theme={theme}>
          <Component {...pageProps} />
        </NextUIProvider>
      </>
    )
  );
```

They will load correctly (viewable inside page source & for crawlers), if you do not use `useSSR()` like:
**Example 2:**
```js
  return (
    <>
    <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>EXAMPLE ON TITLE</title>
      <meta name="title" content="TITLE" />
      <meta name="description" content="DESCRIPTION" />
    </Head>
    <NextUIProvider theme={theme}>
      <Component {...pageProps} />
    </NextUIProvider>
  </>
  );
```

But then there's problems with SSR and getting bombed with `When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.`. 

I have tried adding the following to `package.json` as noted in https://github.com/nextui-org/nextui/issues/779 with no success: 
```JSON
  "resolutions": {
    "@react-aria/ssr": "^3.4.1",
    "@react-aria/table": "^3.5.0"
  },
```

I tried the suggestion by https://github.com/nextui-org/nextui/issues/1038#issuecomment-1435346390 with no success:
```js
  return (
    <SSRProvider>
      <NextUIProvider theme={theme}>
        <Component {...pageProps} />
      </NextUIProvider>
    </SSRProvider>
  );
```

### Steps to Reproduce the Bug or Issue

1) Use same examples as above. You can reproduce it by using `useSSR()`, while conditionally loading all components. 
2) Check `Page Source` in your browser to see if your `<meta/>` can be localised.

### Expected behavior

Metatags will load correctly inside Page Source and be available to e.g. Google, Facebook, LinkedIn.

### Operating System Version

Windows

### Browser

Chrome

**Comment by usamaa-saleem** [comment]
Which browser are you using?

**Comment by moloch--** [comment]
I'm having similar issues, but I'm using an embedded webview, so I can't build the project anymore as `isBrowser` seems to return false:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at l (/frontend/node_modules/@nextui-org/react/cjs/utils/css-transition.js:1:746)
    at div
    at Styled.div
    at p (frontend/node_modules/@nextui-org/react/cjs/progress/progress.js:1:973)
    at div
    at Styled.div
    at div
    at Styled.div
```

**Comment by janathanni** [comment]
@moloch--
I also have same issue, but I didn't use any embedded webview. 
I just used ProgressBar from NextUI, but this erorr just occured for me. 
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at l (C:\account-book\client\node_modules\@nextui-org\react\cjs\utils\css-transition.js:1:746)
    at div
    at Styled.div
    at p (C:\account-book\client\node_modules\@nextui-org\react\cjs\progress\progress.js:1:973)
    at div
    at Styled.div
    at C:\account-book\client\node_modules\@nextui-org\react\cjs\container\container.js:1:843
    at TodayGraphBar (webpack-internal:///./src/Components/Daily/TodayGraphBar.js:17:3)
    at div
    at Styled.div
    at C:\account-book\client\node_modules\@nextui-org\react\cjs\card\card.js:1:313
    at div
    at TodayGoal (webpack-internal:///./src/Components/Daily/TodayGoal.js:24:3)
    at div
    at Daily (webpack-internal:///./src/Components/Daily/Daily.js:28:3)
    at div
    at Styled.div
    at C:\account-book\client\node_modules\@nextui-org\react\cjs\container\container.js:1:843
    at div
    at Main (webpack-internal:///./src/pages/main.js:80:54)
    at div
    at $0775ea8ea6a0565e$var$OverlayContainerDOM (C:\account-book\client\node_modules\@react-aria\overlays\dist\main.js:742:55)
    at $0775ea8ea6a0565e$export$178405afcd8c5eb (C:\account-book\client\node_modules\@react-aria\overlays\dist\main.js:706:21)
    at $0775ea8ea6a0565e$export$bf688221f59024e5
    at $29383e587d62412a$export$9f8ac96af4b1b2ae (C:\account-book\client\node_modules\@nextui-org\react\node_modules\@react-aria\ssr\dist\main.js:25:28)
    at v.disableBaseline (C:\account-book\client\node_modules\@nextui-org\react\cjs\theme\theme-provider.js:1:1046)
    at $704cf1d3b684cc5c$export$9f8ac96af4b1b2ae (file:///C:/account-book/client/node_modules/@react-aria/ssr/dist/import.mjs:39:37)
    at MyApp (webpack-internal:///./src/pages/_app.js:29:3)
    at StyleRegistry (C:\account-book\client\node_modules\styled-jsx\dist\index\index.js:449:36)
    at PathnameContextProviderAdapter (C:\account-book\client\node_modules\next\dist\shared\lib\router\adapters.js:60:11)
    at AppContainer (C:\account-book\client\node_modules\next\dist\server\render.js:294:29)
    at AppContainerWithIsomorphicFiberStructure (C:\account-book\client\node_modules\next\dist\server\render.js:330:57)
    at div
    at Body (C:\account-book\client\node_modules\next\dist\server\render.js:620:21)
When server rendering, you must wrap your application in an <SSRProvider> to ensure consistent ids are generated between the client and server.

**Comment by jrgarciadev** [comment]
Hey guys sorry for the delay please upgrade to [V2](https://nextui.org/docs/guide/upgrade-to-v2), SSR Provider is no longer needed.
