### ISSUE TITLE
[BUG] - Console errors while using Table pagination

### ISSUE THREAD

**Issue by a-Marino** [nextui-org/nextui#1208]
### Describe the bug

Im using NextUI V2 and im getting all kinds of errors in console, even though the table works well

VM2787:1 Warning: [object Object]: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:4716:36
    at ul
    at nav
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:5136:7
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:14325:8
    at div
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:14320:7
    at UsersList (http://localhost:5173/src/components/UsersList.jsx?t=1689719851261:21:3)
    at div
    at App (http://localhost:5173/src/App.jsx:23:29)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21122:32)
    at $f57aed4a881a3485$export$178405afcd8c5eb (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21089:9)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:15398:9)
    at NextUIProvider (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21473:25)

VM2787:1 Warning: [object Object]: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:4716:36
    at ul
    at nav
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:5136:7
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:14325:8
    at div
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:14320:7
    at UsersList (http://localhost:5173/src/components/UsersList.jsx?t=1689719851261:21:3)
    at div
    at App (http://localhost:5173/src/App.jsx:23:29)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21122:32)
    at $f57aed4a881a3485$export$178405afcd8c5eb (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21089:9)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:15398:9)
    at NextUIProvider (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21473:25)
eval @ VM2787:1
overrideMethod @ console.js:213
printWarning @ react.development.js:209
error @ react.development.js:183
warnAboutAccessingKey @ react.development.js:660
(anónimas) @ chunk-ZDOVSCRX.mjs:9
renderWithHooks @ react-dom.development.js:16305
updateForwardRef @ react-dom.development.js:19226
beginWork @ react-dom.development.js:21636
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Mostrar 16 marcos más
VM2787:1 Warning: Invalid ARIA attribute `ariaLabel`. Did you mean `aria-label`?
    at nav
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:5136:7
    at div
    at div
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:14325:8
    at div
    at http://localhost:5173/node_modules/.vite/deps/@nextui-org_react.js?v=e52b2e2a:14320:7
    at UsersList (http://localhost:5173/src/components/UsersList.jsx?t=1689719851261:21:3)
    at div
    at App (http://localhost:5173/src/App.jsx:23:29)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21122:32)
    at $f57aed4a881a3485$export$178405afcd8c5eb (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21089:9)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:15398:9)
    at NextUIProvider (http://localhost:5173/node_modules/.vite/deps/chunk-D75SYHTG.js?v=e52b2e2a:21473:25)

### Steps to Reproduce the Bug or Issue

open console

### Expected behavior

No errors

### Screenshots or Videos

![image](https://github.com/nextui-org/nextui/assets/70865138/3482ff02-51ab-4fa5-924a-5a52fa442bbf)
![image](https://github.com/nextui-org/nextui/assets/70865138/282c0a02-ed46-41fd-b4e6-3c8381111877)
![image](https://github.com/nextui-org/nextui/assets/70865138/7ebe1a22-49aa-442e-b86b-4a99f459da00)
![image](https://github.com/nextui-org/nextui/assets/70865138/8a997399-018f-4748-9dd1-d77519e042fb)

### Operating System Version

Windows

### Browser

Opera

**Comment by jrgarciadev** [comment]
Please test this again with the latest version

**Comment by a-Marino** [comment]
> Please test this again with the latest version

Errors still shows on console
