### ISSUE TITLE
[BUG] - Warning: useLayoutEffect does nothing on the server for Dropdown and Popover

### ISSUE THREAD

**Issue by dmythro** [nextui-org/nextui#1386]
### NextUI Version

2.0.18

### Dropdown

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at file:///Users/.../node_modules/@nextui-org/popover/dist/chunk-UGAU2Q7B.mjs:16:11
    at Dropdown (file:///Users/.../node_modules/@nextui-org/dropdown/dist/chunk-EEFCSOKJ.mjs:14:11)
    at div
    at file:///Users/.../node_modules/@nextui-org/navbar/dist/chunk-PSG7VTZC.mjs:13:11
    at header
```

### Popover

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at file:///.../node_modules/@nextui-org/popover/dist/chunk-UGAU2Q7B.mjs:16:11
    at footer
```

### Your Example Website or App

https://github.com/dmythro/dmythro.com

### Steps to Reproduce the Bug or Issue

1. Create NextJS app
2. Add Navbar with a Dropdown, DropdownTrigger

### Expected behavior

No warning in console, works as expected on client

### Operating System Version

macOS

### Browser

Chrome

**Comment by jrgarciadev** [comment]
Fix on its way: https://github.com/nextui-org/nextui/commit/40633626991d11f251619508f151dd7f435bda25
