### ISSUE TITLE
[BUG] - Not able to use ThemeSwitcher component in NextJS as described in doc

### ISSUE THREAD

**Issue by gaurav6386** [nextui-org/nextui#1441]
### NextUI Version

2.0.24

### Describe the bug

When I try to add a theme switcher component inside of my NextJS app, I am getting the following error which is suggesting me to change ThemeSwitcher component to a client components
```sh
- error node_modules/next-themes/dist/index.js (1:223) @ createContext
- error createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at eval (webpack-internal:///(rsc)/./node_modules/next-themes/dist/index.js:11:92)
    at (rsc)/./node_modules/next-themes/dist/index.js (/home/.../../client/.next/server/app/page.js:1005:1)
    at __webpack_require__ (/home/../../client/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/components/ThemeSwitcher.tsx:7:69)
    at (rsc)/./src/components/ThemeSwitcher.tsx (/home/.../client/.next/server/app/page.js:1670:1)
    at __webpack_require__ (/home/../../../client/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:11:94)
    at (rsc)/./src/app/layout.tsx (/home/../../client/.next/server/app/page.js:1621:1)
    at Function.__webpack_require__ (/home/.../../client/.next/server/webpack-runtime.js:33:42)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:533:9)
    at process.processTimers (node:internal/timers:507:7)
    at async MetadataTree (/home/.../../node_modules/next/dist/lib/metadata/metadata.js:43:51) {
  name: 'Error',
  digest: '4157283239'
}

- error Failed to generate static paths for /:
TypeError: e.createContext is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/next-themes/dist/index.js:11:92)
    at (rsc)/./node_modules/next-themes/dist/index.js (/home/.../client/.next/server/app/page.js:1005:1)
    at __webpack_require__ (/home/.../client/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/components/ThemeSwitcher.tsx:7:69)
    at (rsc)/./src/components/UIRegistry/ThemeSwitcher.tsx (/home/.../client/.next/server/app/page.js:1670:1)
    at __webpack_require__ (/home/.../client/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:11:94)
    at (rsc)/./src/app/layout.tsx (/home/.../client/.next/server/app/page.js:1621:1)
    at Function.__webpack_require__ (/home/.../client/.next/server/webpack-runtime.js:33:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'TypeError'
}
```
The code is exactly as described in doc:
```tsx
//layout.tsx
import { Provider } from './provider'
import { ThemeSwitcher } from '@/components/ThemeSwitcher'
import '@/styles//globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider attribute="class" defaultTheme="dark">
          <ThemeSwitcher />
          {children}
        </Provider>
      </body>
    </html>
  )
}

//./provider.tsx
'use client'

import { ThemeProvider as NextThemesProvider } from "next-themes"
import { type ThemeProviderProps } from "next-themes/dist/types"
import { NextUIProvider } from "@nextui-org/react"
 
export function Provider({ children, ...props }: ThemeProviderProps) {
  return (
    <NextUIProvider>
      <NextThemesProvider {...props}>
        {children}
      </NextThemesProvider>
    </NextUIProvider>
  )
}

//@/components/ThemeSwitcher.tsx
import {useTheme} from "next-themes";

export function ThemeSwitcher() {
  const { theme, setTheme } = useTheme()

  return (
    <div>
      The current theme is: {theme}
      <button onClick={() => setTheme('light')}>Light Mode</button>
      <button onClick={() => setTheme('dark')}>Dark Mode</button>
    </div>
  )
};
```

### Steps to Reproduce the Bug or Issue

1. Create a basic nextjs application
2. Add the components mentioned above into your project
3. Start the nextjs server
4. You will get the above error

### Expected behavior

The expected behavior of the page is to load with a button for toggling themes.

### Operating System Version

Linux

### Browser

Chrome

**Comment by Tuan2002** [comment]
In NextJS 13, you must use "use client" in the top file to force CSR, because the react hooks only work in client component, it doesn't  work in server componemt. More info: [https://nextjs.org/docs/getting-started/react-essentials#client-components](url)

**Comment by gaurav6386** [comment]
I have already tried using the "use client" and it gives the following hydration error in NextJS.
```bash
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

Warning: Expected server HTML to contain a matching text node for "dark" in <div>.

See more info here: https://nextjs.org/docs/messages/react-hydration-error

Component Stack
div
ThemeSwitcher
./src/components/ThemeSwitcher.tsx (13:86)
```

**Comment by Tuan2002** [comment]
> I have already tried using the "use client" and it gives the following hydration error in NextJS. If anyone has recreated this issue try running the same code with "use client" it still gives the following error.
> 
> ```shell
> Unhandled Runtime Error
> Error: Hydration failed because the initial UI does not match what was rendered on the server.
> 
> Warning: Expected server HTML to contain a matching text node for "dark" in <div>.
> 
> See more info here: https://nextjs.org/docs/messages/react-hydration-error
> 
> Component Stack
> div
> ThemeSwitcher
> ./src/components/ThemeSwitcher.tsx (13:86)
> ```
> 
> ![image](https://user-images.githubusercontent.com/60260013/261859841-caa960ec-da48-4ef4-a646-a579ec6536ba.png)
> 
> The inclusion of this client-side component appears to conflict with the underlying server-side rendering (SSR) mechanism of Next.js.

You can try move ThemeSwitcher into wrapper client component (e.g Navbar, Dropdown,...)
