### ISSUE TITLE
it is error after testing  with jest

### ISSUE THREAD

**Issue by chanthavong** [nextui-org/nextui#148]
**Describe the bug**
A clear and concise description.

Code page
```javascript

import Head from 'next/head';
import Image from 'next/image';
import Styles from '../styles/Home.module.css';

import { Button } from '@nextui-org/react';

export default function Home() {
  return (
    <div className={Styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={Styles.main}>
        Home
        <h1>Welcome to Next.js!</h1>
        <Button>Hello</Button>
      </main>

      <footer className={Styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={Styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}


```

My testing code
```javascript

import { render, screen } from "@testing-library/react";
import App from "../src/pages/index";

describe("App", () => {
  it("renders without crashing", () => {
    render(<App />);
    expect(
      screen.getByRole("heading", { name: "Welcome to Next.js!" })
    ).toBeInTheDocument();
  });
});

```

Error text
```javascript


Cannot find module '@nextui-org/react' from 'src/pages/index.js'

    Require stack:
      src/pages/index.js
      test/index.test.js

      3 | import Styles from '../styles/Home.module.css';
      4 |
    > 5 | import  Button  from '@nextui-org/react';
        | ^
      6 |
      7 | export default function Home() {
      8 |   return (

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/pages/index.js:5:1)
```

**Comment by jrgarciadev** [comment]
Hey @chanthavong it looks like `@nextui-org/react` is not installed in your project, could you try to install it again?
