### ISSUE TITLE
Uncaught TypeError: (0 , _react.createStitches) is not a function

### ISSUE THREAD

**Issue by LGR3VE** [nextui-org/nextui#169]
When creating a blank react app (`npx create-react-app my-app`), installing the latest NextUi package (1.0.2-beta.2) and importing 
`import {NextUIProvider} from "@nextui-org/react";`

I get the following error:
```
stitches.config.js:23 Uncaught TypeError: (0 , _react.createStitches) is not a function
    at Object../node_modules/@nextui-org/react/esm/theme/stitches.config.js (stitches.config.js:23:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Object../node_modules/@nextui-org/react/esm/theme/theme-context.js (theme-context.js:10:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Object../node_modules/@nextui-org/react/esm/use-theme/use-theme.js (use-theme.js:10:1)
    at Object.options.factory (react refresh:6:1)
```

**Comment by jrgarciadev** [comment]
Hey @LGR3VE unfortunately in the last version of `react-scripts` (v5) appear this problem, we are working to resolve it, a workaround is to downgrade the `react-scripts` library to version 4 -> here's a detailed explanation https://github.com/nextui-org/nextui/issues/154#issuecomment-1019497379, I will close this issue because it's duplicated here's the firs one -> https://github.com/nextui-org/nextui/issues/154

Hope this helps 🙌🏻
