### ISSUE TITLE
Error when spinning up NextJS app for first time

### ISSUE THREAD

**Issue by brettdoyle44** [nextui-org/nextui#179]
Hello,

When I spin up NextJS via npm run dev I consistently get the following error in the console.

```
Warning: Received `false` for a non-boolean attribute `sm`.

If you want to write it to the DOM, pass a string instead: sm="false" or sm={value.toString()}.

If you used to conditionally omit it with sm={condition && value}, pass sm={condition ? value : undefined} instead.
    at h1
    at Styled.p
    at TextChild (/Users/brett/project-tavern/node_modules/@nextui-org/react/cjs/text/child.js:27:3)
    at TextChild (/Users/brett/project-tavern/node_modules/@nextui-org/react/cjs/text/child.js:27:3)
    at Text (/Users/brett/project-tavern/node_modules/@nextui-org/react/cjs/text/text.js:50:3)
    at Text (/Users/brett/project-tavern/node_modules/@nextui-org/react/cjs/text/text.js:50:3)
    at div
    at Styled.div
    at div
    at Styled.div
    at NavBar
    at div
    at Styled.div
    at Layout (webpack-internal:///./components/Layout.tsx:32:19)
    at SsrProvider (/Users/brett/project-tavern/node_modules/@nextui-org/react/cjs/theme/ssr-provider.js:38:3)
    at ThemeProvider (/Users/brett/project-tavern/node_modules/@nextui-org/react/cjs/theme/theme-provider.js:37:10)
    at exports.ThemeProvider (/Users/brett/project-tavern/node_modules/next-themes/dist/index.js:1:1552)
    at MyApp (webpack-internal:///./pages/_app.tsx:48:18)
    at StyleRegistry (/Users/brett/project-tavern/node_modules/styled-jsx/dist/stylesheet-registry.js:231:34)
    at AppContainer (/Users/brett/project-tavern/node_modules/next/dist/server/render.js:390:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/brett/project-tavern/node_modules/next/dist/server/render.js:420:57)
    at div
    at Body (/Users/brett/project-tavern/node_modules/next/dist/server/render.js:688:21)
```

I am not using the 'sm' option anywhere in the application currently - so this seems to be an issue in the package?

**Comment by Remeic** [comment]
Hi, there is already a bug for this
#161
