### ISSUE TITLE
[BUG] -Select & Dropdown, type.getCollectionNode is not a function

### ISSUE THREAD

**Issue by TeoConan** [nextui-org/nextui#1958]
### NextUI Version

2.2.9

### Describe the bug

Hi everyone

I tried to create a simple `select` in a NextJS framework and Astro
It's working fine on NextJS, but not Astro

I get this error on Astro :

```
TypeError: type.getCollectionNode is not a function
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (.../astro-ui/node_modules/@react-stately/collections/dist/import.mjs:207:35)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (.../astro-ui/node_modules/@react-stately/collections/dist/import.mjs:161:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (.../astro-ui/node_modules/@react-stately/collections/dist/import.mjs:289:22)
    at Generator.next (<anonymous>)
    at new $a02d57049d202695$export$d085fb9e920b5ca7 (.../astro-ui/node_modules/@react-stately/list/dist/import.mjs:80:18)
    at .../astro-ui/node_modules/@react-stately/list/dist/import.mjs:111:129
```

Here my AstroJS code (not working)
```astro
---
import Layout from "../layouts/Layout.astro";
import { Select, SelectItem } from "@nextui-org/react";
---

<Layout title="Welcome to Astro.">
  <main>
    <div class="container mx-auto py-32">
      <div class="mt-16">
        <div class="flex w-full flex-wrap md:flex-nowrap gap-4">
          <Select client:visible label="Select an animal" className="max-w-xs">
            <SelectItem key="1" value="1">Lion</SelectItem>
            <SelectItem key="2" value="2">Tiger</SelectItem>
            <SelectItem key="3" value="3">Elephant</SelectItem>
          </Select>
        </div>
      </div>
    </div>
  </main>
</Layout>
```

My Layout and my provider :
```astro
---
import { NextUIProvider } from "@nextui-org/react";
import { ThemeProvider } from "next-themes";

interface Props {
  title: string;
}

const { title } = Astro.props;
---

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="description" content="Astro description" />
    <meta name="viewport" content="width=device-width" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="generator" content={Astro.generator} />
    <title>{title}</title>
  </head>
  <body>
    <NextUIProvider>
      <ThemeProvider>
        <slot />
      </ThemeProvider>
    </NextUIProvider>
  </body>
</html>
<style is:global></style>
```

And my working code on NextJS :

```js
"use client";

import React from "react";
import { Select, SelectItem } from "@nextui-org/react";

export default function Home() {
  return (
    <main className="container mx-auto py-24 gap-y-12 flex-col">
      <div>
        <Select label="Select an animal" className="max-w-xs">
          <SelectItem key="1" value="1">
            Lion
          </SelectItem>
          <SelectItem key="2" value="2">
            Tiger
          </SelectItem>
          <SelectItem key="3" value="3">
            Elephant
          </SelectItem>
        </Select>
      </div>
    </main>
  );
}
```

It could because of the notion of `use client` / `client:visible` but I don't know why
If anyone got an idea...

### Steps to Reproduce the Bug or Issue

1. Create a Astro project with `npm create astro@latest`
2. Install Tailwind on your project with `npx astro add tailwind`
3. Follow steps from https://nextui.org/docs/frameworks/astro
4. Fill your `Layout.astro` and `index.astro` with the code above
5. Run and get an error

### Expected behavior

Get a working select like in NextJS

### Screenshots or Videos

<img width="1263" alt="image" src="https://github.com/nextui-org/nextui/assets/22664730/5bae6456-ed18-44cb-bfde-85c0a02b121f">

### Operating System Version

macOS M1

### Browser

Chrome

**Comment by chengluliu** [comment]
me too

**Comment by akomm** [comment]
Actually. That must be it. The key definition is in the `.astro` file. So the key will not get the "special" treat it gets in react context. Can you  try the following just for confirmation:

Wrap the entire `Select` that is in the `.astro` file into its own REACT component + file. Then use the new component in the `.astro` file.
