### ISSUE TITLE
[BUG] - Navbar

### ISSUE THREAD

**Issue by LunatikDev** [nextui-org/nextui#2516]
### NextUI Version

2.2.10

### Describe the bug

When clicking on the dropdown component it generates an Unhandled Runtime Error, i used the code provided here: https://nextui.org/docs/components/navbar (Navbar with dropdown)

here are the error log as seen in Chrome Dev Tools Console:

app-index.js:33 Warning: Cannot update a component (`HotReload`) while rendering a different component (`ForwardRef(NextUI.Menu)`). To locate the bad setState() call inside `ForwardRef(NextUI.Menu)`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at Menu (webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/menu/dist/chunk-B24OILC2.mjs:36:67)
    at $9bf71ea28793e738$export$20e40289641fbbb6 (webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/focus/dist/import.mjs:109:21)
    at div
    at div
    at div
    at MotionComponent (webpack-internal:///(app-pages-browser)/./node_modules/framer-motion/dist/es/motion/index.mjs:49:65)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/react-remove-scroll/dist/es2015/UI.js:23:50)
    at div
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/popover/dist/chunk-ARECNDSB.mjs:31:11)
    at DropdownMenu (webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/dropdown/dist/chunk-SXHEBZUY.mjs:21:99)
    at $9bf71ea28793e738$export$20e40289641fbbb6 (webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/focus/dist/import.mjs:109:21)
    at $f1ab8c75478c6f73$export$cf75428e0b9ed1ea (webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/interactions/dist/import.mjs:747:64)
    at $337b884510726a0d$export$c6fdb837b070b4ff (webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/overlays/dist/import.mjs:1421:75)
    at PresenceChild (webpack-internal:///(app-pages-browser)/./node_modules/framer-motion/dist/es/components/AnimatePresence/PresenceChild.mjs:15:26)
    at AnimatePresence (webpack-internal:///(app-pages-browser)/./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs:72:28)
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/popover/dist/chunk-I7AEEVL3.mjs:23:11)
    at Dropdown (webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/dropdown/dist/chunk-FHP3QEBP.mjs:19:11)
    at ul
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/navbar/dist/chunk-PSG7VTZC.mjs:20:11)
    at header
    at nav
    at eval (webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/navbar/dist/chunk-CMNN5TJ7.mjs:27:11)
    at div
    at f (webpack-internal:///(app-pages-browser)/./node_modules/next-themes/dist/index.module.js:8:597)
    at $ (webpack-internal:///(app-pages-browser)/./node_modules/next-themes/dist/index.module.js:8:348)
    at $ea8dcbcb9ea1b556$export$323e4fc2fa4753fb (webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/utils/dist/import.mjs:508:21)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/overlays/dist/import.mjs:1069:54)
    at $f57aed4a881a3485$export$178405afcd8c5eb (webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/overlays/dist/import.mjs:1036:21)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $18f2051aff69b9bf$export$a54013f0d02a8f82 (webpack-internal:///(app-pages-browser)/./node_modules/@react-aria/i18n/dist/real-module.mjs:170:19)
    at NextUIProvider (webpack-internal:///(app-pages-browser)/./node_modules/@nextui-org/system/dist/chunk-HRMF5D3P.mjs:15:3)
    at Providers (webpack-internal:///(app-pages-browser)/./src/app/providers.tsx:19:11)
    at body
    at html
    at InnerLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:241:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:72:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:80:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at LoadingBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:338:11)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:130:11)
    at InnerScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:152:9)
    at ScrollAndFocusHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:227:11)
    at RenderFromTemplateContext (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/render-from-template-context.js:15:44)
    at OuterLayoutRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/layout-router.js:348:11)
    at RedirectErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:72:9)
    at RedirectBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/redirect-boundary.js:80:11)
    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/dev-root-not-found-boundary.js:32:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:297:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:158:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:100:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:130:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:441:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:127:11)
    at RSCComponent
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:143:11)
window.console.error @ app-index.js:33
Show 1 more frame
Show less
import.mjs:219 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20367:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20416:16)
    at invokeGuardedCallback (react-dom.development.js:20491:29)
    at beginWork (react-dom.development.js:26669:7)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at performSyncWorkOnRoot (react-dom.development.js:24633:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
redirect-boundary.js:56 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at beginWork (react-dom.development.js:26647:14)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at performSyncWorkOnRoot (react-dom.development.js:24633:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
not-found-boundary.js:22 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at beginWork (react-dom.development.js:26647:14)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at performSyncWorkOnRoot (react-dom.development.js:24633:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
redirect-boundary.js:56 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at beginWork (react-dom.development.js:26647:14)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at performSyncWorkOnRoot (react-dom.development.js:24633:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
not-found-boundary.js:22 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at beginWork (react-dom.development.js:26647:14)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at performSyncWorkOnRoot (react-dom.development.js:24633:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
import.mjs:219 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20367:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20416:16)
    at invokeGuardedCallback (react-dom.development.js:20491:29)
    at beginWork (react-dom.development.js:26669:7)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at recoverFromConcurrentError (react-dom.development.js:24381:20)
    at performSyncWorkOnRoot (react-dom.development.js:24645:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
redirect-boundary.js:56 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at beginWork (react-dom.development.js:26647:14)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at recoverFromConcurrentError (react-dom.development.js:24381:20)
    at performSyncWorkOnRoot (react-dom.development.js:24645:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
not-found-boundary.js:22 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at beginWork (react-dom.development.js:26647:14)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at recoverFromConcurrentError (react-dom.development.js:24381:20)
    at performSyncWorkOnRoot (react-dom.development.js:24645:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
redirect-boundary.js:56 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at beginWork (react-dom.development.js:26647:14)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at recoverFromConcurrentError (react-dom.development.js:24381:20)
    at performSyncWorkOnRoot (react-dom.development.js:24645:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
not-found-boundary.js:22 Uncaught Error: Unknown element <[object Object]> in collection.
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.getFullNode (import.mjs:219:23)
    at getFullNode.next (<anonymous>)
    at $eb2240fc39a57fa5$export$bf788dd355e3a401.iterateCollection (import.mjs:175:26)
    at iterateCollection.next (<anonymous>)
    at [Symbol.iterator] (import.mjs:303:22)
    at Generator.next (<anonymous>)
    at new $05ca4cd7c4a5a999$export$863faf230ee2118a (import.mjs:87:18)
    at eval (import.mjs:118:159)
    at eval (import.mjs:330:16)
    at mountMemo (react-dom.development.js:12349:5)
    at Object.useMemo (react-dom.development.js:13047:16)
    at useMemo (react.development.js:1771:21)
    at $7613b1592d41b092$export$6cd28814d92fa9c9 (import.mjs:324:65)
    at $875d6693e12af071$export$728d6ba534403756 (import.mjs:118:90)
    at useMenu (chunk-R4ZQ5Y3Q.mjs:47:87)
    at Menu (chunk-B24OILC2.mjs:36:67)
    at renderWithHooks (react-dom.development.js:10930:18)
    at updateForwardRef (react-dom.development.js:15574:20)
    at beginWork$1 (react-dom.development.js:18317:16)
    at beginWork (react-dom.development.js:26647:14)
    at performUnitOfWork (react-dom.development.js:25493:12)
    at workLoopSync (react-dom.development.js:25209:5)
    at renderRootSync (react-dom.development.js:25164:7)
    at recoverFromConcurrentError (react-dom.development.js:24381:20)
    at performSyncWorkOnRoot (react-dom.development.js:24645:20)
    at flushSyncWorkAcrossRoots_impl (react-dom.development.js:10195:13)
    at flushSyncWorkOnAllRoots (react-dom.development.js:10155:3)
    at processRootScheduleInMicrotask (react-dom.development.js:10300:3)
    at eval (react-dom.development.js:10471:7)
app-index.js:33 The above error occurred in the <NotFoundErrorBoundary> component:

    at NotFoundErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:54:9)
    at NotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/not-found-boundary.js:62:11)
    at DevRootNotFoundBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/dev-root-not-found-boundary.js:32:11)
    at ReactDevOverlay (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:297:11)
    at Router (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:158:11)
    at ErrorBoundaryHandler (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:100:9)
    at ErrorBoundary (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/error-boundary.js:130:11)
    at AppRouter (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/components/app-router.js:441:13)
    at ServerRoot (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:127:11)
    at RSCComponent
    at Root (webpack-internal:///(app-pages-browser)/./node_modules/next/dist/client/app-index.js:143:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ReactDevOverlay.
window.console.error @ app-index.js:33
Show 1 more frame
Show less

### Steps to Reproduce the Bug or Issue

copy code provided here: https://nextui.org/docs/components/navbar (Navbar with dropdown)
then try the component

### Expected behavior

the dropdown menu should open 

### Operating System Version

Windows 10

### Browser

Chrome

**Comment by LunatikDev** [comment]
NOTE: i tried to add "use client" and it works, is this component client only?

**Comment by zainkhas** [comment]
I have the same question. Shouldn't the menu be server-compatible? This is where some of the most important links going to be which require SSR.
