### ISSUE TITLE
Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element. 

### ISSUE THREAD

**Issue by xushaoxiao** [nextui-org/nextui#2593]
### NextUI Version

2.2.10

### Describe the bug

Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at ap (/Users/shaoxixu/repos/vdna-mono/frontend/vdnax/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+popover@2.1.15_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@18_gkrcnwyrxol7ft6cikewwoddve/node_modules/@nextui-org/popover/dist/chunk-K4VREUER.mjs:25:113)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+dropdown@2.1.17_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@1_jcm6p4e3f63y6chdc3cz24sr6m/node_modules/@nextui-org/dropdown/dist/chunk-63RZRIL7.mjs:17:106)
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+popover@2.1.15_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@18_gkrcnwyrxol7ft6cikewwoddve/node_modules/@nextui-org/popover/dist/chunk-I7AEEVL3.mjs:23:11)
    at Dropdown (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+dropdown@2.1.17_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@1_jcm6p4e3f63y6chdc3cz24sr6m/node_modules/@nextui-org/dropdown/dist/chunk-FHP3QEBP.mjs:19:11)
    at div
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+navbar@2.0.27_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@18._aa53oj6mpjpnf4cduu4q4wgjqm/node_modules/@nextui-org/navbar/dist/chunk-PSG7VTZC.mjs:20:11)
    at header
    at nav
    at eval (webpack-internal:///(ssr)/./node_modules/.pnpm/@nextui-org+navbar@2.0.27_@nextui-org+system@2.0.15_@nextui-org+theme@2.1.18_@types+react@18._aa53oj6mpjpnf4cduu4q4wgjqm/node_modules/@nextui-org/navbar/dist/chunk-CMNN5TJ7.mjs:27:11)
    at Lazy
    at div
    at body
    at html
    at RedirectErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:71:9)
    at RedirectBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/redirect-boundary.js:79:11)
    at ReactDevOverlay (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:66:9)
    at HotReload (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:298:11)
    at Router (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:154:11)
    at ErrorBoundaryHandler (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:99:9)
    at ErrorBoundary (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/error-boundary.js:128:11)
    at AppRouter (webpack-internal:///(ssr)/./node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/client/components/app-router.js:426:13)
    at Lazy
    at Lazy
    at /Users/shaoxixu/repos/vdna-mono/frontend/vdnax/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:374733
    at /Users/shaoxixu/repos/vdna-mono/frontend/vdnax/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:374733
    at ServerInsertedHTMLProvider (/Users/shaoxixu/repos/vdna-mono/frontend/vdnax/node_modules/.pnpm/next@14.0.0_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:38:23140)

### Steps to Reproduce the Bug or Issue

Warning: React does not recognize the `originalProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originalprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element. 

### Expected behavior

how to fix it.

### Operating System Version

macOS

### Browser

Chrome

**Comment by Tosters** [comment]
The same warning is shown when this is added in the <Navbar />

```
<DropdownTrigger>
  <Avatar
  isBordered
  as="button"
  className="transition-transform"
  color="secondary"
  name="Jason Hughes"
  size="sm"
  src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
  />
</DropdownTrigger>
```

Following the example in: https://nextui.org/docs/components/navbar#with-avatar

**Comment by slytter** [comment]
+1

**Comment by Lemirq** [comment]
Same problem here +1. Mine shows this error and that `React does not recognize the 'isDisabled' prop on a DOM element....`  Both of these are on the DropdownTrigger

**Comment by AkhilsWorkshop** [comment]
Is it fixed? If yes, how to update it?

**Comment by wingkwong** [comment]
@AkhilsWorkshop fixed but not released yet. please wait for the next release.

**Comment by halesyy** [comment]
I still get this issue - nothing dire, just annoying to have an error on each dev process of the website.

**Comment by QuadraKOfx** [comment]
@wingkwong thanks a lot :) To we have an ETA for the next release? Just an fyi

**Comment by wingkwong** [comment]
@QuadraKOfx target on Apr 15. See [here](https://github.com/nextui-org/nextui/milestone/20)

**Comment by Mikecrochip** [comment]
this still occurs. any update?

**Comment by wingkwong** [comment]
@Mikecrochip please create a new issue

**Comment by Issacgpu** [comment]
i have the same issue too

**Comment by Issacgpu** [comment]
is it fixed now?

**Comment by wingkwong** [comment]
@Issacgpu are you using the latest version? if so, please share a minimal reproducible example.
