### ISSUE TITLE
[BUG] - Link component doesn't work

### ISSUE THREAD

**Issue by dongchunxu** [nextui-org/nextui#3031]
### NextUI Version

latest

### Describe the bug

`import { Link } from "@nextui-org/link";
  <Link href="/login" size="sm">Login</Link>`
An error occurred when I clicked、
The error detail:
Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at addPathPrefix (add-path-prefix.js:13:15)
    at addBasePath (add-base-path.js:15:114)
    at eval (app-router.js:158:58)
    at eval (app-router.js:282:21)
    at startTransition (react.development.js:2597:25)
    at push (app-router.js:280:44)
    at eval (openLink.mjs:41:85)
    at $ea8dcbcb9ea1b556$var$getSyntheticLink (openLink.mjs:100:46)
    at Object.open (openLink.mjs:40:17)
    at onClick (index.mjs:51:18)
    at HTMLUnknownElement.callCallback (react-dom.development.js:20565:14)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:16)
    at invokeGuardedCallback (react-dom.development.js:20689:29)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:20703:25)
    at executeDispatch (react-dom.development.js:32128:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:32160:7)
    at processDispatchQueue (react-dom.development.js:32173:5)
    at dispatchEventsForPlugins (react-dom.development.js:32184:3)
    at eval (react-dom.development.js:32374:12)
    at batchedUpdates$1 (react-dom.development.js:24953:12)
    at batchedUpdates (react-dom.development.js:28844:12)
    at dispatchEventForPluginEventSystem (react-dom.development.js:32373:3)
    at dispatchEvent (react-dom.development.js:30141:5)
    at dispatchDiscreteEvent (react-dom.development.js:30112:5)

### Steps to Reproduce the Bug or Issue

1.import { Link } from "@nextui-org/link";
2.   <Link href="/login" size="sm">Login</Link>

### Expected behavior

I hope to jump correctly

### Operating System Version

macos

### Browser

Chrome

**Comment by wingkwong** [comment]
duplicate - https://github.com/nextui-org/nextui/issues/2934

the fix will be available in next release.

**Comment by tensorboy** [comment]
> duplicate - #2934
> 
> the fix will be available in next release.

when the next release will happen?

**Comment by wingkwong** [comment]
@tensorboy Sorry for the late. There is a few large PRs still being reviewed. We'll release it after that. It should happen in the coming days.
