### ISSUE TITLE
[BUG] - NextUI Turbopack throw error: "createContext only works in Client Components"

### ISSUE THREAD

**Issue by assad-skipbau** [nextui-org/nextui#3967]
### NextUI Version

2.4.8

### Describe the bug

Newly installed NextJS version with turbopack causing this issue: `createContext only works in Client Components`
I did not create any new compoents yet, just the basic setup and it throws this error. 
disabling the turbopack solves the issue.

Here is the whole error:
```
TypeError: createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at [project]/node_modules/@react-aria/ssr/dist/SSRProvider.mjs [app-rsc] (ecmascript) (file://C:\Projects\test\.next\server\chunks\ssr\node_modules_94f3b1._.js:643:270)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/@react-aria/utils/dist/useId.mjs [app-rsc] (ecmascript) (file://C:\Projects\test\.next\server\chunks\ssr\node_modules_94f3b1._.js:205:166)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/@react-aria/utils/dist/mergeProps.mjs [app-rsc] (ecmascript) (file://C:\Projects\test\.next\server\chunks\ssr\node_modules_94f3b1._.js:325:162)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/@react-aria/visually-hidden/dist/VisuallyHidden.mjs [app-rsc] (ecmascript) (file://C:\Projects\test\.next\server\chunks\ssr\node_modules_94f3b1._.js:770:167)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/@nextui-org/react/dist/index.mjs [app-rsc] (ecmascript) <exports> (file://C:\Projects\test\.next\server\chunks\ssr\node_modules_94f3b1._.js:12904:184)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/src/app/providers.tsx [app-rsc] (ecmascript) (file://C:\Projects\test\.next\server\chunks\ssr\src_app_9a2348._.js:13:179)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript) (file://C:\Projects\test\.next\server\chunks\ssr\src_app_9a2348._.js:36:128)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component) (file://C:\Projects\test\.next\server\chunks\ssr\src_app_9a2348._.js:72:32)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => "[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico [app-rsc] (static)\" } [app-rsc] (structured image object, ecmascript, Next.js server component)", MODULE_1 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) <module evaluation> (file://C:\Projects\test\.next\server\chunks\ssr\node_modules_next_c6ada2._.js:2508:160)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at getOrInstantiateModuleFromParent (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:644:12)
    at esmImport (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:132:20)
    at [project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/page { METADATA_0 => "[project]/src/app/favicon.ico.mjs { IMAGE => \"[project]/src/app/favicon.ico [app-rsc] (static)\" } [app-rsc] (structured image object, ecmascript, Next.js server component)", MODULE_1 => "[project]/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)", MODULE_2 => "[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)", MODULE_3 => "[project]/src/app/page.tsx [app-rsc] (ecmascript, Next.js server component)" } [app-rsc] (ecmascript) (file://C:\Projects\test\.next\server\chunks\ssr\node_modules_next_c6ada2._.js:2607:1025)
    at instantiateModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:589:23)
    at instantiateRuntimeModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:652:12)
    at Object.getOrInstantiateRuntimeModule (file://C:\Projects\test\.next\server\chunks\ssr\[turbopack]_runtime.js:668:12)
    at Object.<anonymous> (file://C:\Projects\test\.next\server\app\page.js:15:26)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (file://C:\Projects\test\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at requirePage (file://C:\Projects\test\node_modules\next\dist\server\require.js:103:84)
    at loadComponentsImpl (file://C:\Projects\test\node_modules\next\dist\server\load-components.js:99:57)
```

### Steps to Reproduce the Bug or Issue

Just create a new basic NextJs project and follow the **manual** setup instructions of the NextUI

### Expected behavior

not sure

### Operating System Version

windows 11 

### Browser

Chrome

**Comment by wingkwong** [comment]
please share a sandbox for us to investigate.

**Comment by whitewooood** [comment]
same problem happen on next.js 15 with react 19.

**Comment by wingkwong** [comment]
currently the production version is not supporting react 19. errors are expected in this case. we're working on it.

**Comment by assad-skipbau** [comment]
> please share a sandbox for us to investigate.

How do i share a sandbox?
In general it is as whitewooood said above _next.js 15 with react 19_ i am just installing them togather and there we go, the error happens. as i mentioned, turning turbopack off solves the issue.

**Comment by ahammond3aws** [comment]
Is there any update on this issue please? Am experiencing the same behaviour on v15.0.3 with react 18. Turning turbopack off solves this too but would be good to have a better performing dev environment

**Comment by assad-skipbau** [comment]
> Is there any update on this issue please? Am experiencing the same behaviour on v15.0.3 with react 18. Turning turbopack off solves this too but would be good to have a better performing dev environment

No, just stop using turbopack or stop using nextui

**Comment by wingkwong** [comment]
you can share the sandbox using stackblitz or a sample repo so that we could check if there is misconfiguration or incorrect version being used. We've a beta version that's supporting nextjs 15 and react 19.

**Comment by keplerbb01** [comment]
Import HeroUI/NextUI components from individual packages instead of the main @nextui/react or @heroui/react package:

❌ Don't do this:
`import { Button } from "@heroui/react";`

✅ Do this instead:
`import { Button } from "@heroui/button";`

**Comment by hugs7** [comment]
> Import HeroUI/NextUI components from individual packages instead of the main @nextui/react or @heroui/react package:
> 
> ❌ Don't do this: `import { Button } from "@heroui/react";`
> 
> ✅ Do this instead: `import { Button } from "@heroui/button";`

We shouldn't have to do this though
