### ISSUE TITLE
[BUG] - Inputs has no roles by default.

### ISSUE THREAD

**Issue by SalahAdDin** [nextui-org/nextui#415]
### Describe the bug

We created hour website using this elegant library.

There is time to test the forms we created and we get the following error:
```
● Test suite failed to run

    TestingLibraryElementError: Unable to find an accessible element with the role "textbox" and name `/Title/`

    There are no accessible roles. But there might be some inaccessible roles. If you wish to access them, then set the `hidden` option to `true`. Learn more about this here: https://testing-library.com/docs/dom-testing-library/api-queries#byrole

    Ignored nodes: comments, <script />, <style />
    <body />

      16 | };
      17 |
    > 18 | const titleInput = screen.getByRole<HTMLInputElement>('textbox', {
         |                           ^
      19 |   name: /Title/,
      20 | });
      21 |

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:38:19)
      at node_modules/@testing-library/dom/dist/query-helpers.js:90:38
      at node_modules/@testing-library/dom/dist/query-helpers.js:62:17
      at node_modules/@testing-library/dom/dist/query-helpers.js:111:19
      at Object.<anonymous> (src/presentation/widgets/forms/PutReminderForm.test.tsx:18:27)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
```

We used the same line we used with **MUI** based websites, but it didn't work here.

### Steps to Reproduce the Bug or Issue

1. Run tests.

### Expected behavior

It should return all available roles to query by.

### Operating System Version

5.15.28-1 Manjaro Linux x86_64

### Browser

Other (add additonal context)

**Comment by danielsimao** [comment]
@jrgarciadev, have you ever considered encapsulating the logic for the label and helperText in a external component, such as `TextField` or `FormField`. In that component, you could gather a nit way to allow customisation on the label and helperText. Including all in the Input component, seems like too much. What do you think?

**Comment by jrgarciadev** [comment]
Hey @danielsimao yes I have considered that, I would like to implement something like the `@react-aria/spectrum` has https://github.com/adobe/react-spectrum/tree/main/packages/%40react-spectrum/label/src, it would be great to have those components alongside the `Radio`, `Checkbox` and `Input` components

**Comment by jrgarciadev** [comment]
Hey please upgrade to V2 since V1 will no receive more updates.

**Comment by SalahAdDin** [comment]
@jrgarciadev did you solve this issue?

**Comment by jrgarciadev** [comment]
Hey @SalahAdDin yes please upgrade to v2, the Input component is now based on react-aria hooks https://react-spectrum.adobe.com/react-aria/useTextField.html#usetextfield
