### ISSUE TITLE
[BUG] - 2.6.2 PopoverTrigger via DropdownTrigger ref warning in console

### ISSUE THREAD

**Issue by daveycodez** [nextui-org/nextui#4245]
### NextUI Version

2.6.2

### Describe the bug

```
client.js:85 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `NextUI.DropdownTrigger`.
    at PopoverTrigger (webpack-internal:///./node_modules/@nextui-org/popover/dist/chunk-2JMNEOKT.mjs:24:113)
    at DropdownTrigger (webpack-internal:///./node_modules/@nextui-org/dropdown/dist/chunk-733ZIL44.mjs:15:106)
    at eval (webpack-internal:///./node_modules/@nextui-org/popover/dist/chunk-XRF5IYSD.mjs:23:11)
    at Dropdown (webpack-internal:///./node_modules/@nextui-org/dropdown/dist/chunk-GBNLLUVD.mjs:19:11)
```

### Steps to Reproduce the Bug or Issue

Use a DropdownTrigger or PopoverTrigger

### Expected behavior

No ref warnings in console

### Operating System Version

macOS

### Browser

Chrome

**Comment by daveycodez** [comment]
This appears to happen on any DropdownTrigger in 2.6.2, just copied and pasted it in from the docs and seeing this warning

**Comment by ryankashi** [comment]
I'm getting the same.

```
client.js:85 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `NextUI.DropdownTrigger`.
    at PopoverTrigger (webpack-internal:///./node_modules/@nextui-org/popover/dist/chunk-2JMNEOKT.mjs:24:113)
    at DropdownTrigger (webpack-internal:///./node_modules/@nextui-org/dropdown/dist/chunk-733ZIL44.mjs:15:106)
    at eval (webpack-internal:///./node_modules/@nextui-org/popover/dist/chunk-XRF5IYSD.mjs:23:11)
    at Dropdown (webpack-internal:///./node_modules/@nextui-org/dropdown/dist/chunk-GBNLLUVD.mjs:19:11)
```

With "@nextui-org/dropdown": "^2.1.31",

**Comment by wingkwong** [comment]
please share your package.json. thanks.

**Comment by AnYiEE** [comment]
I also encountered this issue. I'm using React 18.3.1 and NextUI 2.6.3

**Comment by daveycodez** [comment]
> please share your package.json. thanks.
> 
> some findings (assuming using latest version):
> 
> * able to reproduce in react 18.3.1
> * not able to reproduce in react 19

```
{
  "name": "daveyplate",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "dev": "next dev & nodemon --exec node code-sync.js --quiet",
    "ngrok": "ngrok http --domain=leaked.ngrok.dev 3000",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "export": "NEXT_PUBLIC_IS_EXPORT=1 sh export.sh",
    "postinstall": "react-flagpack",
    "generate-icons": "generate-icons --source ./public/icons/icon-512.png",
    "stripe:listen": "stripe listen --forward-to=localhost:3000/api/webhooks --project-name=daveyplate"
  },
  "dependencies": {
    "@capacitor/android": "^5.7.6",
    "@capacitor/app": "^5.0.8",
    "@capacitor/browser": "^5.2.1",
    "@capacitor/core": "^5.7.6",
    "@capacitor/ios": "^5.7.6",
    "@capacitor/network": "^5.0.8",
    "@daveyplate/generate-icons": "^1.0.4",
    "@daveyplate/next-cors-middleware": "^1.0.1",
    "@daveyplate/next-open-graph": "^1.0.2",
    "@daveyplate/next-page-title": "^1.0.3",
    "@daveyplate/next-rate-limit": "^1.0.8",
    "@daveyplate/nextui-confirm-modal": "^1.0.5",
    "@daveyplate/nextui-crop-image-modal": "^1.0.5",
    "@daveyplate/nextui-fixed-avatar": "^1.0.6",
    "@daveyplate/supabase-auth-nextui": "^1.0.5",
    "@daveyplate/supabase-swr-entities": "^3.0.22",
    "@daveyplate/tailwind-drag-dropzone": "^1.0.4",
    "@daveyplate/use-scroll-restoration": "^1.0.4",
    "@daveyplate/use-window-focus-blur": "^1.0.0",
    "@heroicons/react": "^2.1.5",
    "@iamtraction/google-translate": "^2.0.1",
    "@next/bundle-analyzer": "^15.0.3",
    "@nextui-org/react": "^2.6.4",
    "@piotr-cz/swr-idb-cache": "^1.0.3",
    "@sidekickicons/react": "^0.7.0",
    "@supabase/auth-helpers-react": "^0.5.0",
    "@supabase/auth-ui-react": "^0.4.7",
    "@supabase/auth-ui-shared": "^0.1.8",
    "@supabase/postgrest-js": "^1.16.3",
    "@supabase/ssr": "^0.5.1",
    "@supabase/supabase-js": "^2.45.6",
    "@uidotdev/usehooks": "^2.4.1",
    "@vercel/analytics": "^1.3.2",
    "@vercel/speed-insights": "^1.0.14",
    "compressorjs": "^1.2.1",
    "dotenv": "^16.4.5",
    "framer-motion": "^11.11.10",
    "javascript-time-ago": "^2.5.11",
    "micro": "^10.0.1",
    "next": "^15.0.2",
    "next-auto-translate": "^1.0.56",
    "next-intl": "^3.23.5",
    "next-language-detector": "^1.1.0",
    "next-themes": "^0.4.3",
    "node-gzip": "^1.1.2",
    "nodemon": "^3.1.7",
    "nuqs": "^2.2.3",
    "peerjs": "^1.5.4",
    "pulltorefreshjs": "^0.1.22",
    "react": "^18.3.1",
    "react-avatar-editor": "^13.0.2",
    "react-device-detect": "^2.2.3",
    "react-dom": "^18.3.1",
    "react-flagpack": "^2.0.6",
    "react-simple-wysiwyg": "^3.1.3",
    "react-swipe-to-delete-ios": "^2.1.0",
    "react-time-ago": "^7.3.3",
    "sonner": "^1.7.0",
    "stripe": "^17.2.1",
    "swr": "^2.2.5",
    "tailwindcss": "^3.4.14",
    "tailwindcss-animate": "^1.0.7",
    "tailwindcss-safe-area": "^0.6.0",
    "uuid": "^11.0.2",
    "yet-another-react-lightbox": "^3.21.1"
  },
  "devDependencies": {
    "@capacitor/cli": "^5.7.0",
    "@iconify/react": "^5.1.0",
    "@types/react": "^18.3.13",
    "autoprefixer": "^10.4.20",
    "eslint": "9.16.0",
    "eslint-config-next": "15.0.4",
    "file-loader": "^6.2.0",
    "husky": "^9.1.6"
  },
  "packageManager": "npm@10.5.0"
}
```

I'm unable to get React 19 to work. But it would make sense because React 19 no longer requires forwardRef.

**Comment by bearsworth** [comment]
Came here to say I did not get this error in previous Next UI version 2.4 but now I'm getting this error in a dropdown copy and pasted from an example.

**Comment by Nienormalny** [comment]
Same here, i updated React 18 to React 19 and updated NextUi to 2.6.4. After that i get error:
```
Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `NextUI.DropdownTrigger`.
```

And as `<DropdownTrigger>` children i used normal React.ReactNode.

Any ideas how to fix this problem?

Btw. App works fine, but this warning is kind of "Hey im still here and i will f**k you in the future, if you will not fix me."

**Comment by Tosters** [comment]
Hi!
Just updated to "@nextui-org/react": "^2.6.4" and started to get the warning in Console.

`chunk-NUMECXU6.js?v=f92ad345:521 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `NextUI.DropdownTrigger`...`

Still on ` "react": "^18.3.1"` though.
