### ISSUE TITLE
flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.

### ISSUE THREAD

**Issue by depyronick** [nextui-org/nextui#917]
### Describe the bug

```
  "dependencies": {
    "@next/font": "^13.0.5",
    "@nextui-org/react": "^1.0.0-beta.11-dbg1", <-- don't mind this, same on .10
    "@react-aria/ssr": "^3.4.0",
    "@stripe/react-stripe-js": "^1.14.2",
    "@stripe/stripe-js": "^1.42.1",
    "axios": "^1.1.3",
    "date-fns": "^2.29.3",
    "next": "13.0.5",
    "next-auth": "^4.15.1",
    "next-themes": "^0.2.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "sass": "1.56.0",
    "stripe": "^10.17.0",
    "swiper": "^8.4.4",
    "typescript": "4.8.4",
    "validator": "^13.7.0"
  },
  "devDependencies": {
    "@types/node": "18.11.9",
    "@types/react": "17.0.11",
    "@types/react-dom": "17.0.8",
    "@types/validator": "^13.7.10"
  }
```

```
Warning: flushSync was called from inside a lifecycle method. React cannot flush when React is already rendering. Consider moving this call to a scheduler task or micro task.
    at a (webpack-internal:///./node_modules/@nextui-org/react/esm/utils/css-transition.js:7:28)
    at $9bf71ea28793e738$export$20e40289641fbbb6 (webpack-internal:///./node_modules/@react-aria/focus/dist/module.js:76:21)
    at eval (webpack-internal:///./node_modules/@nextui-org/react/esm/popover/popover-content.js:17:89)
    at eval (webpack-internal:///./node_modules/@nextui-org/react/esm/dropdown/dropdown-menu.js:17:83)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (webpack-internal:///./node_modules/@react-aria/overlays/dist/module.js:751:55)
    at $f57aed4a881a3485$export$178405afcd8c5eb (webpack-internal:///./node_modules/@react-aria/overlays/dist/module.js:715:21)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $f57aed4a881a3485$export$b47c3594eab58386 (webpack-internal:///./node_modules/@react-aria/overlays/dist/module.js:762:74)
    at eval (webpack-internal:///./node_modules/@nextui-org/react/esm/popover/popover.js:10:89)
    at m (webpack-internal:///./node_modules/@nextui-org/react/esm/dropdown/dropdown.js:10:28)
    at Login
    at ul
    at Styled.ul
    at eval (webpack-internal:///./node_modules/@nextui-org/react/esm/navbar/navbar-content.js:14:91)
    at div
    at Styled.div
    at nav
    at Styled.nav
    at eval (webpack-internal:///./node_modules/@nextui-org/react/esm/navbar/navbar.js:15:91)
    at FUINavbar (webpack-internal:///./components/fui/fui-navbar/fui-navbar.tsx:37:78)
    at div
    at $f57aed4a881a3485$var$OverlayContainerDOM (webpack-internal:///./node_modules/@react-aria/overlays/dist/module.js:751:55)
    at $f57aed4a881a3485$export$178405afcd8c5eb (webpack-internal:///./node_modules/@react-aria/overlays/dist/module.js:715:21)
    at $f57aed4a881a3485$export$bf688221f59024e5
    at $704cf1d3b684cc5c$export$9f8ac96af4b1b2ae (webpack-internal:///./node_modules/@nextui-org/react/node_modules/@react-aria/ssr/dist/module.js:23:64)
    at __webpack_exports__.default.disableBaseline (webpack-internal:///./node_modules/@nextui-org/react/esm/theme/theme-provider.js:15:138)
    at f (webpack-internal:///./node_modules/next-themes/dist/index.module.js:8:597)
    at $ (webpack-internal:///./node_modules/next-themes/dist/index.module.js:8:348)
    at main
    at SessionProvider (webpack-internal:///./node_modules/next-auth/react/index.js:446:24)
    at $704cf1d3b684cc5c$export$9f8ac96af4b1b2ae (webpack-internal:///./node_modules/@react-aria/ssr/dist/module.js:23:64)
    at FuupsAI (webpack-internal:///./pages/_app.tsx:73:11)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:3325)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:6707)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:60:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:173:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:346:11)
```

### Steps to Reproduce the Bug or Issue

Wherever there is animation.

### Expected behavior

Not to throw the error.

### Operating System Version

Windows

### Browser

Chrome

**Comment by tianenpang** [comment]
Hi @depyronick thanks for your feedback, it's been fixed here https://github.com/nextui-org/nextui/pull/785
